### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by Hironsan** [Hironsan/google-vision-sampler#2]
add reference for each feature

**Comment by saigutta** [comment]
Traceback (most recent call last):
  File "logo_detection.py", line 48, in <module>
    main(args.image_file)
  File "logo_detection.py", line 41, in main
    logo = response['responses'][0]['logoAnnotations'][0]['description']
KeyError: 'responses'


I'm getting this error for every file

**Comment by ToMas-hack** [comment]
The same error
Traceback (most recent call last):
  File "text_detection.py", line 48, in <module>
    main(args.image_file)
  File "text_detection.py", line 41, in main
    text = response['responses'][0]['textAnnotations'][0]['description']
KeyError: 'responses'
